import { AuthContextProvider } from '../context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} px-4  bg-zinc-900 text-zinc-100`}>
        <AuthContextProvider>
          {children}

        </AuthContextProvider>
  
      </body>
    </html>
  )
}
